# Generated by Django 3.1.9 on 2023-11-23 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='titre',
            new_name='title',
        ),
    ]
